const CHARACTERS = [
{id:"nezha",name:"哪吒",origin:"東方",hp:24,emoji:"🔥",tag:"高速爆發",skill:"乾坤圈",skillCost:3,skillCd:0,desc:"造成5點傷害；若本回合已使用功能牌，額外+2。",c1:"#8f2437",c2:"#e9a64b"},
{id:"wukong",name:"孫悟空",origin:"東方",hp:25,emoji:"🐒",tag:"變化反制",skill:"金箍棒",skillCost:3,skillCd:0,desc:"造成6點傷害；若對手本回合使用防禦牌，改為4點。",c1:"#6d3e19",c2:"#d6a33e"},
{id:"erlang",name:"二郎神",origin:"東方",hp:27,emoji:"👁️",tag:"情報反制",skill:"三尖兩刃刀",skillCost:3,skillCd:0,desc:"造成5點傷害；若對手上一張牌是攻擊牌，額外+2。",c1:"#243b73",c2:"#caa95c"},
{id:"nuwa",name:"女媧",origin:"東方",hp:30,emoji:"🐍",tag:"防禦恢復",skill:"補天",skillCost:4,skillCd:0,desc:"恢復5 HP，每場最多2次。",c1:"#4b786c",c2:"#d7bd6b"},
{id:"chang_e",name:"嫦娥",origin:"東方",hp:23,emoji:"🌙",tag:"資源控制",skill:"廣寒封印",skillCost:3,skillCd:0,desc:"封鎖對手一張隨機手牌，持續1回合。",c1:"#3d4b8a",c2:"#b7d4ff"},
{id:"houyi",name:"后羿",origin:"東方",hp:26,emoji:"🏹",tag:"遠程爆發",skill:"射日",skillCost:4,skillCd:0,desc:"造成8傷害；下回合不能使用攻擊牌。",c1:"#7b4323",c2:"#e4c36b"},
{id:"jingwei",name:"精衛",origin:"東方",hp:22,emoji:"🐦",tag:"受傷累積",skill:"精衛之志",skillCost:2,skillCd:0,desc:"每次受傷累積1意志；技能消耗全部意志，每層造成1傷害。",c1:"#2d5d6b",c2:"#e5a4b8"},
{id:"zhongkui",name:"鍾馗",origin:"東方",hp:28,emoji:"👹",tag:"驅散反制",skill:"伏魔",skillCost:3,skillCd:0,desc:"造成4傷害並移除自己1個負面效果。",c1:"#3c2633",c2:"#b64246"},
{id:"amaterasu",name:"天照大神",origin:"東方",hp:27,emoji:"☀️",tag:"光明續航",skill:"天岩戶之光",skillCost:4,skillCd:0,desc:"恢復4 HP，且本回合下一次傷害-3。",c1:"#6e4922",c2:"#f5df9a"},
{id:"susanoo",name:"須佐之男",origin:"東方",hp:28,emoji:"⚔️",tag:"低血爆發",skill:"天叢雲",skillCost:4,skillCd:0,desc:"造成8傷害；若HP≤12，改為10。",c1:"#263e5b",c2:"#a8d0dd"},
{id:"tsukuyomi",name:"月讀命",origin:"東方",hp:24,emoji:"🌑",tag:"手牌壓制",skill:"月蝕",skillCost:3,skillCd:0,desc:"對手隨機棄1張；若手牌≤3則改為造成3傷害。",c1:"#1f2b52",c2:"#a58ac9"},
{id:"izanagi",name:"伊邪那岐",origin:"東方",hp:29,emoji:"⛩️",tag:"續戰復生",skill:"淨化",skillCost:3,skillCd:0,desc:"恢復3 HP並移除1個負面效果。第一次死亡時保留1 HP。",c1:"#4a5a4d",c2:"#d8d2bd"},
{id:"hanuman",name:"哈努曼",origin:"東方",hp:27,emoji:"🐒",tag:"受擊反擊",skill:"筋斗飛躍",skillCost:2,skillCd:0,desc:"本回合下一次受傷害-4。",c1:"#7a3d24",c2:"#d59d57"},
{id:"shiva",name:"濕婆",origin:"東方",hp:26,emoji:"🔱",tag:"毀滅蓄力",skill:"第三眼",skillCost:5,skillCd:0,desc:"造成6+毀滅層數傷害，使用後清除毀滅。",c1:"#26345f",c2:"#9d75a9"},
{id:"garuda",name:"迦樓羅",origin:"東方",hp:25,emoji:"🦅",tag:"破防突襲",skill:"金翅撕裂",skillCost:3,skillCd:0,desc:"造成5傷害並摧毀對手1個持續防禦效果。",c1:"#6a421d",c2:"#e2c269"},
{id:"zeus",name:"宙斯",origin:"西方",hp:28,emoji:"⚡",tag:"雷霆爆發",skill:"雷霆之怒",skillCost:4,skillCd:0,desc:"造成7傷害。被動有機率讓第一次攻擊額外+2。",c1:"#263d70",c2:"#c5cce0"},
{id:"athena",name:"雅典娜",origin:"西方",hp:29,emoji:"🛡️",tag:"防守反擊",skill:"神盾反擊",skillCost:3,skillCd:0,desc:"下一次受傷-3並反彈3傷害。",c1:"#435d76",c2:"#d7b873"},
{id:"hades",name:"哈迪斯",origin:"西方",hp:27,emoji:"💀",tag:"棄牌冥魂",skill:"冥王召喚",skillCost:4,skillCd:0,desc:"每棄一張牌累積冥魂；技能每個冥魂造成2傷害。",c1:"#241e3c",c2:"#8c4c7d"},
{id:"medusa",name:"美杜莎",origin:"西方",hp:24,emoji:"🐍",tag:"石化控制",skill:"石化",skillCost:4,skillCd:0,desc:"對手下回合只能使用1張功能牌。",c1:"#274d47",c2:"#a6b968"},
{id:"heracles",name:"赫拉克勒斯",origin:"西方",hp:32,emoji:"🦁",tag:"力量累積",skill:"獅皮重擊",skillCost:3,skillCd:0,desc:"每受一次攻擊累積試煉；造成4+試煉層數傷害。",c1:"#684020",c2:"#d7ad62"},
{id:"loki",name:"洛基",origin:"西方",hp:23,emoji:"🃏",tag:"欺騙混亂",skill:"幻象",skillCost:3,skillCd:0,desc:"對手下一次攻擊有50%機率反噬自己。",c1:"#2d3d4c",c2:"#8b5b9e"},
{id:"thor",name:"索爾",origin:"西方",hp:30,emoji:"🔨",tag:"蓄力爆發",skill:"米奧爾尼爾",skillCost:4,skillCd:0,desc:"每次攻擊累積雷霆；技能造成5+雷霆層數傷害。",c1:"#3c5676",c2:"#d1ad62"},
{id:"odin",name:"奧丁",origin:"西方",hp:26,emoji:"🪶",tag:"情報資源",skill:"犧牲之智",skillCost:2,skillCd:0,desc:"棄1張牌抽2張牌。每3回合可查看對手2張手牌。",c1:"#252c42",c2:"#8e9fb7"},
{id:"freya",name:"芙蕾雅",origin:"西方",hp:25,emoji:"🌹",tag:"治療魅惑",skill:"魅惑",skillCost:3,skillCd:0,desc:"對手下一張攻擊牌傷害-4。",c1:"#6c3d62",c2:"#d7a7b9"},
{id:"anubis",name:"阿努比斯",origin:"西方",hp:27,emoji:"⚖️",tag:"斬殺判定",skill:"審判",skillCost:5,skillCd:0,desc:"對手HP≤8時造成8，否則造成4。",c1:"#3b3428",c2:"#c49c5b"},
{id:"ra",name:"拉",origin:"西方",hp:29,emoji:"☀️",tag:"持續灼熱",skill:"太陽爆裂",skillCost:4,skillCd:0,desc:"造成6傷害並附加灼熱：下回合再受2。",c1:"#73451e",c2:"#f0c45e"},
{id:"osiris",name:"奧西里斯",origin:"西方",hp:28,emoji:"🌿",tag:"墓地循環",skill:"冥界循環",skillCost:3,skillCd:0,desc:"從棄牌堆取回一張1～2費功能牌。",c1:"#284936",c2:"#b3b36d"},
{id:"morrigan",name:"莫莉甘",origin:"西方",hp:25,emoji:"🐦‍⬛",tag:"詛咒預兆",skill:"烏鴉預兆",skillCost:3,skillCd:0,desc:"對手下一次受到傷害時額外+3。",c1:"#24253d",c2:"#8c4960"},
{id:"gilgamesh",name:"吉爾伽美什",origin:"西方",hp:29,emoji:"👑",tag:"寶庫全能",skill:"天之鎖",skillCost:4,skillCd:0,desc:"造成5傷害；若對手本回合用過技能，額外+3。",c1:"#665020",c2:"#d9bf72"},
{id:"cernunnos",name:"角神塞爾努諾斯",origin:"西方",hp:30,emoji:"🦌",tag:"自然循環",skill:"荒野降臨",skillCost:4,skillCd:0,desc:"造成4傷害並恢復4 HP。",c1:"#294936",c2:"#b4a06b"}
];

const CARDS = [
["strike","神罰雷擊",2,"攻擊","造成4點傷害。"],["fire","烈焰爆裂",2,"攻擊","造成3點傷害，附加灼熱1回合。"],
["pierce","穿刺",2,"攻擊","造成4點傷害，無視1點護盾。"],["double","連續斬擊",3,"攻擊","造成2+2傷害，可分別被防禦。"],
["crush","毀滅衝擊",3,"攻擊","造成6傷害，自己受到1傷害。"],["soul","靈魂撕裂",3,"攻擊","造成4傷害，對手下一次恢復-2。"],
["thunder","雷霆貫穿",4,"攻擊","造成7傷害；若上回合用過攻擊則不能使用。"],["backstab","背刺",2,"攻擊","若對手本回合已用牌，造成5；否則2。"],
["shield","神盾",2,"防禦","抵消4點傷害。"],["light","護體神光",3,"防禦","抵消6點傷害。"],["mirror","鏡面反射",3,"防禦","下一次傷害減半，剩餘傷害反彈。"],["dodge","閃避",2,"防禦","下一次受傷有50%機率完全閃避。"],["lastwall","最後壁壘",4,"防禦","本回合受到傷害不超過3。"],
["spring","生命之泉",2,"恢復","恢復4 HP。"],["gift","神之恩賜",3,"恢復","恢復6 HP。"],["rebirth","重生之火",4,"恢復","恢復3；若HP≤8改為7。"],["moonbless","月之祝福",2,"恢復","恢復2並抽1張。"],
["seal","封印",3,"控制","對手下回合不能使用角色技能。"],["silence","沉默",2,"控制","指定對手一張手牌，下回合不能使用。"],["chaos","混亂",3,"控制","對手下一張功能牌隨機選擇目標。"],["timestop","時間停止",5,"控制","對手下回合只能使用1張牌。"],["rewind","命運逆轉",4,"控制","取消對手上一張功能牌的效果。"],
["steal","偷竊",2,"手牌","隨機抽取對手一張手牌。"],["peek","窺視",1,"手牌","查看對手3張隨機手牌。"],["swap","交換命運",2,"手牌","雙方各選1張手牌交換。"],["sacrifice","獻祭",1,"手牌","棄1張牌，抽2張。"],["dice","命運之骰",2,"手牌","隨機獲得：抽2／回血4／傷害4／+3神力。"],
["curse","詛咒",2,"詛咒","對手下一次受傷+2。"],["poison","中毒",2,"詛咒","對手連續3回合各受1傷害。"],["burn","灼熱印記",2,"詛咒","對手下次結束回合受3傷害。"],["soulbind","靈魂枷鎖",3,"詛咒","對手下回合每使用一張牌額外耗1神力。"],["weaken","衰弱",2,"詛咒","對手下一張攻擊牌-3。"],
["infuse","神力灌注",0,"神力","立即獲得2神力。"],["pact","神之契約",1,"神力","本回合+4神力，下回合開始失去2。"],["wrath","神怒",2,"神力","下一張攻擊牌+4傷害。"],
["decoy","替身",3,"特殊","受到致命傷害時保留1 HP。"],["rollback","時間回溯",4,"特殊","HP恢復至本回合開始值。"],["stealfate","命運竊取",3,"特殊","複製對手上一張功能牌。"],["mirrorcard","鏡像",4,"特殊","複製自己上一張功能牌。"],["forbidden","禁忌之力",0,"特殊","下一張牌免神力，但自己受3傷害。"],
["ragnarok","諸神黃昏",6,"傳說","雙方各受5傷害，一般防禦不能完全抵消。"],["rewrite","天命改寫",5,"傳說","將雙方HP差距縮小至5。"],["judgment","眾神審判",6,"傳說","造成10傷害；下回合不能用角色技能。"],["chaosfall","混沌降臨",5,"傳說","雙方各棄2張再抽2張。"],["counterstrike","神之逆襲",4,"傳說","僅自己HP較低時可用；造成差距/2，最多7。"],
["deathrefuse","死亡拒絕",5,"傳說","本回合致命傷害改為剩1 HP，每場一次。"],["allone","萬象歸一",5,"傳說","移除所有負面效果並恢復5 HP。"],["coin","命運硬幣",3,"傳說","50%造成8傷害，否則自己受4。"],["domain","神域",5,"傳說","持續2回合，雙方傷害-2。"],["endbell","終焉之鐘",6,"傳說","雙方下回合只能使用1張功能牌。"]
].map((x,i)=>({id:x[0],name:x[1],cost:x[2],type:x[3],desc:x[4],rarity:x[3]==="傳說"?"傳說":x[2]>=4?"史詩":x[2]>=3?"稀有":"普通"}));
